apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfds-dashboard
  namespace: tfds-dashboard
  labels:
    app: tfds-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfds-dashboard
  template:
    metadata:
      labels:
        app: tfds-dashboard
    spec:
      containers:
        - name: tfds-dashboard
          image: tfds-dashboard
          ports:
            - containerPort: 80
          env:
            - name: VITE_INFLUXDB_URL
              value: "https://idea-helsinki-influxdb-helm-webapp.dataportal.fi/"
            - name: VITE_INFLUXDB_ORG
              value: "idea-helsinki"
            - name: VITE_INFLUXDB_BUCKET
              value: "idea-fcd-bucket"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
